"""Generate the Station enum from data/stations.csv."""

import csv
import re
from pathlib import Path


def sanitize_code(code: str) -> str:
    """Sanitize a station code to be a valid Python identifier.

    Args:
        code: Raw station code string.

    Returns:
        Sanitized string safe for use as an enum member name.
    """
    # If starts with a digit, prefix with underscore
    if code[0].isdigit():
        code = "_" + code
    # Replace hyphens/spaces with underscores
    code = re.sub(r"[^A-Z0-9_]", "_", code.upper())
    return code


def generate_station_enum(csv_path: Path, output_path: Path) -> None:
    """Generate the Station enum Python file from a CSV of station data.

    Args:
        csv_path: Path to the stations CSV file (code,name,city,state).
        output_path: Destination .py file for the generated enum.
    """
    stations: list[tuple[str, str]] = []

    with csv_path.open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            code = row["code"].strip()
            name = row["name"].strip()
            city = row["city"].strip()
            state = row["state"].strip()
            label = f"{name} ({city}, {state})"
            stations.append((sanitize_code(code), label))

    lines = [
        '"""Indian Railways station codes."""',
        "",
        "# This file is auto-generated by scripts/generate_station_enum.py.",
        "# Do not edit manually.",
        "",
        "from enum import Enum",
        "",
        "",
        "class Station(str, Enum):",
        '    """Indian Railways station codes (IATA-style identifiers)."""',
        "",
    ]

    for enum_name, label in stations:
        # Escape quotes in label
        label_escaped = label.replace('"', '\\"')
        lines.append(f'    {enum_name} = "{label_escaped}"')

    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {len(stations)} stations → {output_path}")


if __name__ == "__main__":
    repo_root = Path(__file__).parent.parent
    csv_path = repo_root / "data" / "stations.csv"
    output_path = repo_root / "rail" / "models" / "station.py"
    generate_station_enum(csv_path, output_path)
